INSERT INTO 'system_types' ('type_name') VALUES ('Physical');
INSERT INTO 'system_types' ('type_name') VALUES ('Digital');

INSERT INTO 'software_categories' ('category_name') VALUES ('Add-On');
INSERT INTO 'software_categories' ('category_name') VALUES ('Application');
INSERT INTO 'software_categories' ('category_name') VALUES ('Audio');
INSERT INTO 'software_categories' ('category_name') VALUES ('Bonus Disc');
INSERT INTO 'software_categories' ('category_name') VALUES ('Coverdisc');
INSERT INTO 'software_categories' ('category_name') VALUES ('Demo');
INSERT INTO 'software_categories' ('category_name') VALUES ('Educational');
INSERT INTO 'software_categories' ('category_name') VALUES ('Game');
INSERT INTO 'software_categories' ('category_name') VALUES ('Multimedia');
INSERT INTO 'software_categories' ('category_name') VALUES ('Press Kit');
INSERT INTO 'software_categories' ('category_name') VALUES ('Video');

INSERT INTO 'origin_types' ('type_name') VALUES ('Cart');
INSERT INTO 'origin_types' ('type_name') VALUES ('ROM Chip');

INSERT INTO 'regions' ('region_name') VALUES ('ar');
INSERT INTO 'regions' ('region_name') VALUES ('!asia');
INSERT INTO 'regions' ('region_name') VALUES ('au');
INSERT INTO 'regions' ('region_name') VALUES ('at');
INSERT INTO 'regions' ('region_name') VALUES ('br');
INSERT INTO 'regions' ('region_name') VALUES ('bg');
INSERT INTO 'regions' ('region_name') VALUES ('ca');
INSERT INTO 'regions' ('region_name') VALUES ('cn');
INSERT INTO 'regions' ('region_name') VALUES ('cz');
INSERT INTO 'regions' ('region_name') VALUES ('dk');
INSERT INTO 'regions' ('region_name') VALUES ('!europe');
INSERT INTO 'regions' ('region_name') VALUES ('fi');
INSERT INTO 'regions' ('region_name') VALUES ('fr');
INSERT INTO 'regions' ('region_name') VALUES ('de');
INSERT INTO 'regions' ('region_name') VALUES ('gr');
INSERT INTO 'regions' ('region_name') VALUES ('hk');
INSERT INTO 'regions' ('region_name') VALUES ('hu');
INSERT INTO 'regions' ('region_name') VALUES ('it');
INSERT INTO 'regions' ('region_name') VALUES ('jp');
INSERT INTO 'regions' ('region_name') VALUES ('kr');
INSERT INTO 'regions' ('region_name') VALUES ('!latin_america');
INSERT INTO 'regions' ('region_name') VALUES ('mx');
INSERT INTO 'regions' ('region_name') VALUES ('nl');
INSERT INTO 'regions' ('region_name') VALUES ('nz');
INSERT INTO 'regions' ('region_name') VALUES ('no');
INSERT INTO 'regions' ('region_name') VALUES ('pl');
INSERT INTO 'regions' ('region_name') VALUES ('pt');
INSERT INTO 'regions' ('region_name') VALUES ('ru');
INSERT INTO 'regions' ('region_name') VALUES ('es');
INSERT INTO 'regions' ('region_name') VALUES ('se');
INSERT INTO 'regions' ('region_name') VALUES ('tw');
INSERT INTO 'regions' ('region_name') VALUES ('ae');
INSERT INTO 'regions' ('region_name') VALUES ('us');
INSERT INTO 'regions' ('region_name') VALUES ('gb');
INSERT INTO 'regions' ('region_name') VALUES ('!world');

INSERT INTO 'languages' ('ietf_tag') VALUES ('en');
INSERT INTO 'languages' ('ietf_tag') VALUES ('ja');
INSERT INTO 'languages' ('ietf_tag') VALUES ('fr');
INSERT INTO 'languages' ('ietf_tag') VALUES ('de');
INSERT INTO 'languages' ('ietf_tag') VALUES ('es');
INSERT INTO 'languages' ('ietf_tag') VALUES ('it');
INSERT INTO 'languages' ('ietf_tag') VALUES ('nl');
INSERT INTO 'languages' ('ietf_tag') VALUES ('pt');
INSERT INTO 'languages' ('ietf_tag') VALUES ('sv');
INSERT INTO 'languages' ('ietf_tag') VALUES ('no');
INSERT INTO 'languages' ('ietf_tag') VALUES ('da');
INSERT INTO 'languages' ('ietf_tag') VALUES ('fi');
INSERT INTO 'languages' ('ietf_tag') VALUES ('zh');
INSERT INTO 'languages' ('ietf_tag') VALUES ('ko');
INSERT INTO 'languages' ('ietf_tag') VALUES ('pl');
