INSERT INTO 'software_categories' ('category_name') VALUES ('Add-On');
INSERT INTO 'software_categories' ('category_name') VALUES ('Application');
INSERT INTO 'software_categories' ('category_name') VALUES ('Audio');
INSERT INTO 'software_categories' ('category_name') VALUES ('Bonus Disc');
INSERT INTO 'software_categories' ('category_name') VALUES ('Coverdisc');
INSERT INTO 'software_categories' ('category_name') VALUES ('Demo');
INSERT INTO 'software_categories' ('category_name') VALUES ('Educational');
INSERT INTO 'software_categories' ('category_name') VALUES ('Game');
INSERT INTO 'software_categories' ('category_name') VALUES ('Multimedia');
INSERT INTO 'software_categories' ('category_name') VALUES ('Press Kit');
INSERT INTO 'software_categories' ('category_name') VALUES ('Video');
