data = [
	'ar',
	'!asia',
	'au',
	'at',
	'br',
	'bg',
	'ca',
	'cn',
	'cz',
	'dk',
	'!europe',
	'fi',
	'fr',
	'de',
	'gr',
	'hk',
	'hu',
	'it',
	'jp',
	'kr',
	'!latin_america',
	'mx',
	'nl',
	'nz',
	'no',
	'pl',
	'pt',
	'ru',
	'es',
	'se',
	'tw',
	'ae',
	'us',
	'gb',
	'!world'
]
