table! {
    /// Representation of the `dump_files` table.
    ///
    /// (Automatically generated by Diesel.)
    dump_files (dump_id, file_id) {
        /// The `dump_id` column of the `dump_files` table.
        ///
        /// Its SQL type is `Integer`.
        ///
        /// (Automatically generated by Diesel.)
        dump_id -> Integer,
        /// The `file_id` column of the `dump_files` table.
        ///
        /// Its SQL type is `Integer`.
        ///
        /// (Automatically generated by Diesel.)
        file_id -> Integer,
    }
}

table! {
    /// Representation of the `dumps` table.
    ///
    /// (Automatically generated by Diesel.)
    dumps (dump_id) {
        /// The `dump_id` column of the `dumps` table.
        ///
        /// Its SQL type is `Integer`.
        ///
        /// (Automatically generated by Diesel.)
        dump_id -> Integer,
        /// The `origin_id` column of the `dumps` table.
        ///
        /// Its SQL type is `Integer`.
        ///
        /// (Automatically generated by Diesel.)
        origin_id -> Integer,
        /// The `dumper` column of the `dumps` table.
        ///
        /// Its SQL type is `Nullable<Text>`.
        ///
        /// (Automatically generated by Diesel.)
        dumper -> Nullable<Text>,
        /// The `dumper_affiliation` column of the `dumps` table.
        ///
        /// Its SQL type is `Nullable<Text>`.
        ///
        /// (Automatically generated by Diesel.)
        dumper_affiliation -> Nullable<Text>,
        /// The `dumper_trustworthiness` column of the `dumps` table.
        ///
        /// Its SQL type is `Nullable<Text>`.
        ///
        /// (Automatically generated by Diesel.)
        dumper_trustworthiness -> Nullable<Text>,
        /// The `dump_tool` column of the `dumps` table.
        ///
        /// Its SQL type is `Nullable<Text>`.
        ///
        /// (Automatically generated by Diesel.)
        dump_tool -> Nullable<Text>,
        /// The `dump_tool_version` column of the `dumps` table.
        ///
        /// Its SQL type is `Nullable<Text>`.
        ///
        /// (Automatically generated by Diesel.)
        dump_tool_version -> Nullable<Text>,
        /// The `error_count` column of the `dumps` table.
        ///
        /// Its SQL type is `Nullable<Integer>`.
        ///
        /// (Automatically generated by Diesel.)
        error_count -> Nullable<Integer>,
    }
}

table! {
    /// Representation of the `file_sub_files` table.
    ///
    /// (Automatically generated by Diesel.)
    file_sub_files (file_id, sub_file_id) {
        /// The `file_id` column of the `file_sub_files` table.
        ///
        /// Its SQL type is `Integer`.
        ///
        /// (Automatically generated by Diesel.)
        file_id -> Integer,
        /// The `sub_file_id` column of the `file_sub_files` table.
        ///
        /// Its SQL type is `Integer`.
        ///
        /// (Automatically generated by Diesel.)
        sub_file_id -> Integer,
    }
}

table! {
    /// Representation of the `files` table.
    ///
    /// (Automatically generated by Diesel.)
    files (file_id) {
        /// The `file_id` column of the `files` table.
        ///
        /// Its SQL type is `Integer`.
        ///
        /// (Automatically generated by Diesel.)
        file_id -> Integer,
        /// The `file_name` column of the `files` table.
        ///
        /// Its SQL type is `Text`.
        ///
        /// (Automatically generated by Diesel.)
        file_name -> Text,
        /// The `type_general` column of the `files` table.
        ///
        /// Its SQL type is `Nullable<Text>`.
        ///
        /// (Automatically generated by Diesel.)
        type_general -> Nullable<Text>,
        /// The `type_specific` column of the `files` table.
        ///
        /// Its SQL type is `Nullable<Text>`.
        ///
        /// (Automatically generated by Diesel.)
        type_specific -> Nullable<Text>,
        /// The `downloadable` column of the `files` table.
        ///
        /// Its SQL type is `Nullable<Bool>`.
        ///
        /// (Automatically generated by Diesel.)
        downloadable -> Nullable<Bool>,
        /// The `size` column of the `files` table.
        ///
        /// Its SQL type is `Integer`.
        ///
        /// (Automatically generated by Diesel.)
        size -> Integer,
        /// The `crc32` column of the `files` table.
        ///
        /// Its SQL type is `Binary`.
        ///
        /// (Automatically generated by Diesel.)
        crc32 -> Binary,
        /// The `md5` column of the `files` table.
        ///
        /// Its SQL type is `Binary`.
        ///
        /// (Automatically generated by Diesel.)
        md5 -> Binary,
        /// The `sha1` column of the `files` table.
        ///
        /// Its SQL type is `Binary`.
        ///
        /// (Automatically generated by Diesel.)
        sha1 -> Binary,
        /// The `sha256` column of the `files` table.
        ///
        /// Its SQL type is `Binary`.
        ///
        /// (Automatically generated by Diesel.)
        sha256 -> Binary,
        /// The `serial` column of the `files` table.
        ///
        /// Its SQL type is `Nullable<Text>`.
        ///
        /// (Automatically generated by Diesel.)
        serial -> Nullable<Text>,
        /// The `bad` column of the `files` table.
        ///
        /// Its SQL type is `Nullable<Bool>`.
        ///
        /// (Automatically generated by Diesel.)
        bad -> Nullable<Bool>,
        /// The `added_date` column of the `files` table.
        ///
        /// Its SQL type is `Timestamp`.
        ///
        /// (Automatically generated by Diesel.)
        added_date -> Timestamp,
        /// The `file_last_modified` column of the `files` table.
        ///
        /// Its SQL type is `Nullable<Timestamp>`.
        ///
        /// (Automatically generated by Diesel.)
        file_last_modified -> Nullable<Timestamp>,
    }
}

table! {
    /// Representation of the `languages` table.
    ///
    /// (Automatically generated by Diesel.)
    languages (language_id) {
        /// The `language_id` column of the `languages` table.
        ///
        /// Its SQL type is `Integer`.
        ///
        /// (Automatically generated by Diesel.)
        language_id -> Integer,
        /// The `ietf_tag` column of the `languages` table.
        ///
        /// Its SQL type is `Text`.
        ///
        /// (Automatically generated by Diesel.)
        ietf_tag -> Text,
    }
}

table! {
    /// Representation of the `origin_types` table.
    ///
    /// (Automatically generated by Diesel.)
    origin_types (type_id) {
        /// The `type_id` column of the `origin_types` table.
        ///
        /// Its SQL type is `Integer`.
        ///
        /// (Automatically generated by Diesel.)
        type_id -> Integer,
        /// The `type_name` column of the `origin_types` table.
        ///
        /// Its SQL type is `Text`.
        ///
        /// (Automatically generated by Diesel.)
        type_name -> Text,
    }
}

table! {
    /// Representation of the `origins` table.
    ///
    /// (Automatically generated by Diesel.)
    origins (origin_id) {
        /// The `origin_id` column of the `origins` table.
        ///
        /// Its SQL type is `Integer`.
        ///
        /// (Automatically generated by Diesel.)
        origin_id -> Integer,
        /// The `version_id` column of the `origins` table.
        ///
        /// Its SQL type is `Integer`.
        ///
        /// (Automatically generated by Diesel.)
        version_id -> Integer,
        /// The `sub_origin_id` column of the `origins` table.
        ///
        /// Its SQL type is `Integer`.
        ///
        /// (Automatically generated by Diesel.)
        sub_origin_id -> Integer,
        /// The `type_id` column of the `origins` table.
        ///
        /// Its SQL type is `Nullable<Integer>`.
        ///
        /// (Automatically generated by Diesel.)
        type_id -> Nullable<Integer>,
        /// The `edition` column of the `origins` table.
        ///
        /// Its SQL type is `Nullable<Text>`.
        ///
        /// (Automatically generated by Diesel.)
        edition -> Nullable<Text>,
    }
}

table! {
    /// Representation of the `regions` table.
    ///
    /// (Automatically generated by Diesel.)
    regions (region_id) {
        /// The `region_id` column of the `regions` table.
        ///
        /// Its SQL type is `Integer`.
        ///
        /// (Automatically generated by Diesel.)
        region_id -> Integer,
        /// The `region_name` column of the `regions` table.
        ///
        /// Its SQL type is `Text`.
        ///
        /// (Automatically generated by Diesel.)
        region_name -> Text,
    }
}

table! {
    /// Representation of the `software` table.
    ///
    /// (Automatically generated by Diesel.)
    software (software_id) {
        /// The `software_id` column of the `software` table.
        ///
        /// Its SQL type is `Integer`.
        ///
        /// (Automatically generated by Diesel.)
        software_id -> Integer,
        /// The `system_id` column of the `software` table.
        ///
        /// Its SQL type is `Integer`.
        ///
        /// (Automatically generated by Diesel.)
        system_id -> Integer,
        /// The `name` column of the `software` table.
        ///
        /// Its SQL type is `Text`.
        ///
        /// (Automatically generated by Diesel.)
        name -> Text,
        /// The `name_safe` column of the `software` table.
        ///
        /// Its SQL type is `Nullable<Text>`.
        ///
        /// (Automatically generated by Diesel.)
        name_safe -> Nullable<Text>,
        /// The `category_id` column of the `software` table.
        ///
        /// Its SQL type is `Integer`.
        ///
        /// (Automatically generated by Diesel.)
        category_id -> Integer,
    }
}

table! {
    /// Representation of the `software_categories` table.
    ///
    /// (Automatically generated by Diesel.)
    software_categories (category_id) {
        /// The `category_id` column of the `software_categories` table.
        ///
        /// Its SQL type is `Integer`.
        ///
        /// (Automatically generated by Diesel.)
        category_id -> Integer,
        /// The `category_name` column of the `software_categories` table.
        ///
        /// Its SQL type is `Text`.
        ///
        /// (Automatically generated by Diesel.)
        category_name -> Text,
    }
}

table! {
    /// Representation of the `software_regions` table.
    ///
    /// (Automatically generated by Diesel.)
    software_regions (software_id, region_id) {
        /// The `software_id` column of the `software_regions` table.
        ///
        /// Its SQL type is `Integer`.
        ///
        /// (Automatically generated by Diesel.)
        software_id -> Integer,
        /// The `region_id` column of the `software_regions` table.
        ///
        /// Its SQL type is `Integer`.
        ///
        /// (Automatically generated by Diesel.)
        region_id -> Integer,
    }
}

table! {
    /// Representation of the `system_types` table.
    ///
    /// (Automatically generated by Diesel.)
    system_types (type_id) {
        /// The `type_id` column of the `system_types` table.
        ///
        /// Its SQL type is `Integer`.
        ///
        /// (Automatically generated by Diesel.)
        type_id -> Integer,
        /// The `type_name` column of the `system_types` table.
        ///
        /// Its SQL type is `Text`.
        ///
        /// (Automatically generated by Diesel.)
        type_name -> Text,
    }
}

table! {
    /// Representation of the `systems` table.
    ///
    /// (Automatically generated by Diesel.)
    systems (system_id) {
        /// The `system_id` column of the `systems` table.
        ///
        /// Its SQL type is `Integer`.
        ///
        /// (Automatically generated by Diesel.)
        system_id -> Integer,
        /// The `name` column of the `systems` table.
        ///
        /// Its SQL type is `Text`.
        ///
        /// (Automatically generated by Diesel.)
        name -> Text,
        /// The `name_safe` column of the `systems` table.
        ///
        /// Its SQL type is `Nullable<Text>`.
        ///
        /// (Automatically generated by Diesel.)
        name_safe -> Nullable<Text>,
        /// The `type_id` column of the `systems` table.
        ///
        /// Its SQL type is `Integer`.
        ///
        /// (Automatically generated by Diesel.)
        type_id -> Integer,
        /// The `wikidata_item_id` column of the `systems` table.
        ///
        /// Its SQL type is `Nullable<Text>`.
        ///
        /// (Automatically generated by Diesel.)
        wikidata_item_id -> Nullable<Text>,
    }
}

table! {
    /// Representation of the `users` table.
    ///
    /// (Automatically generated by Diesel.)
    users (user_name) {
        /// The `user_name` column of the `users` table.
        ///
        /// Its SQL type is `Text`.
        ///
        /// (Automatically generated by Diesel.)
        user_name -> Text,
        /// The `user_pass_hash` column of the `users` table.
        ///
        /// Its SQL type is `Text`.
        ///
        /// (Automatically generated by Diesel.)
        user_pass_hash -> Text,
        /// The `disabled` column of the `users` table.
        ///
        /// Its SQL type is `Bool`.
        ///
        /// (Automatically generated by Diesel.)
        disabled -> Bool,
        /// The `email` column of the `users` table.
        ///
        /// Its SQL type is `Nullable<Text>`.
        ///
        /// (Automatically generated by Diesel.)
        email -> Nullable<Text>,
    }
}

table! {
    /// Representation of the `version_languages` table.
    ///
    /// (Automatically generated by Diesel.)
    version_languages (version_id, language_id) {
        /// The `version_id` column of the `version_languages` table.
        ///
        /// Its SQL type is `Integer`.
        ///
        /// (Automatically generated by Diesel.)
        version_id -> Integer,
        /// The `language_id` column of the `version_languages` table.
        ///
        /// Its SQL type is `Integer`.
        ///
        /// (Automatically generated by Diesel.)
        language_id -> Integer,
    }
}

table! {
    /// Representation of the `versions` table.
    ///
    /// (Automatically generated by Diesel.)
    versions (version_id) {
        /// The `version_id` column of the `versions` table.
        ///
        /// Its SQL type is `Integer`.
        ///
        /// (Automatically generated by Diesel.)
        version_id -> Integer,
        /// The `software_id` column of the `versions` table.
        ///
        /// Its SQL type is `Integer`.
        ///
        /// (Automatically generated by Diesel.)
        software_id -> Integer,
        /// The `version_string` column of the `versions` table.
        ///
        /// Its SQL type is `Nullable<Text>`.
        ///
        /// (Automatically generated by Diesel.)
        version_string -> Nullable<Text>,
        /// The `contents` column of the `versions` table.
        ///
        /// Its SQL type is `Nullable<Text>`.
        ///
        /// (Automatically generated by Diesel.)
        contents -> Nullable<Text>,
    }
}

joinable!(dump_files -> dumps (dump_id));
joinable!(dump_files -> files (file_id));
joinable!(dumps -> origins (origin_id));
joinable!(origins -> origin_types (type_id));
joinable!(origins -> versions (version_id));
joinable!(software -> software_categories (category_id));
joinable!(software -> systems (system_id));
joinable!(software_regions -> regions (region_id));
joinable!(software_regions -> software (software_id));
joinable!(systems -> system_types (type_id));
joinable!(version_languages -> languages (language_id));
joinable!(version_languages -> versions (version_id));
joinable!(versions -> software (software_id));

allow_tables_to_appear_in_same_query!(
    dump_files,
    dumps,
    file_sub_files,
    files,
    languages,
    origin_types,
    origins,
    regions,
    software,
    software_categories,
    software_regions,
    system_types,
    systems,
    users,
    version_languages,
    versions,
);
